# Generated by Django 4.2.4 on 2023-08-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_address_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super-admin', 'Super Admin'), ('artist-manager', 'Artist Manager'), ('artist', 'Artist')], default='artist', max_length=20),
        ),
    ]
