# Generated by Django 4.2.4 on 2023-08-13 08:52

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(validators=[users.models.User.validate_past_date]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number can be entered in the format: '+977 999999999' or '9999999999'. At least 10 digit needed.", regex='^(\\+\\d{1,3}\\s)?\\d{10}$')]),
        ),
    ]
